### ISSUE TITLE
Show "Regular hours" on location detail cards if values exist

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/parks-rec-finder#146] opened 2018-01-26 21:40 UTC
### Expected Behavior
Show "Regular hours" on location detail cards if values exist

### Observed Behavior
> Steps to Reproduce
http://localhost:8080/parks-rec-finder/#/location/56a8f82c7a8cee5e3a25ae97
![screencapture-localhost-8080-parks-rec-finder-1517002654943](https://user-images.githubusercontent.com/10891276/35461874-9ca29708-02b7-11e8-87bd-1f14a8f01f9c.png)

#### Proposed Solution
![locations_detail view-onopen-belfield](https://user-images.githubusercontent.com/10891276/35461878-a22195c6-02b7-11e8-876a-a4f1db98601c.png)

**Comment by karissademi** [comment] 2018-01-26 21:45
Duplicate of https://github.com/CityOfPhiladelphia/parks-rec-finder/issues/84

**Closed by karissademi** 2018-01-26 21:45 UTC
Labels: bug, priority - high
