### ISSUE TITLE
Longer addresses break over activity list card (when in searched list view), 

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#114] opened 2018-01-23 22:51 UTC
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Observed Behavior
> Steps to Reproduce

1. Opened page
1. Typed into search Bar
1. Cicked Marder

### Screenshot
![image](https://user-images.githubusercontent.com/719422/35305059-f7c1fd26-0065-11e8-9a2d-995ad6d8a3a6.png)

**Comment by timwis** [comment] 2018-01-24 10:54
Duplicate of #115

**Closed by timwis** 2018-01-24 10:54 UTC
Labels: Mobile, design, priority - high
