### ISSUE TITLE
Low contrast on category lists' title text 

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#95] opened 2018-01-12 17:23 UTC
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior
Category titles are readable on all category list photos

### Observed Behavior
View boat launches, places to eat, and older adult centers buttons in particular. White text is not well contrasted to the photo.

#### Proposed Solution

Apply a higher contrast to the photo from white text or an application (border?) to the text itself. 

The on-hover state provides more contrast to this title text. Perhaps leveraging that some. 

### Screenshot
![image](https://user-images.githubusercontent.com/719422/34887099-547f7aba-f793-11e7-9174-790fe9ddcd24.png)

![image](https://user-images.githubusercontent.com/719422/34887112-5d4c93bc-f793-11e7-9243-de57991c2636.png)

**Comment by karissademi** [comment] 2018-01-16 21:58
Duplicate of https://github.com/CityOfPhiladelphia/parks-rec-finder/issues/94

**Closed by karissademi** 2018-01-16 21:58 UTC
