### ISSUE TITLE
How filters affect search results

### ISSUE THREAD

**Issue by moriamiller** [CityOfPhiladelphia/parks-rec-finder#89] opened 2018-01-10 23:51 UTC
Do programs for all ages not appear at all when you add specific age ranges to the filter criteria? 

I was in Educational & Mentoring and selected Youth 6-12, and all of the programs I saw previously that fit within that age range (like this https://beta.phila.gov/parks-rec-finder/#/program/59e9231e9fc23a54dd777812) disappeared.

**Comment by bdolly** [comment] 2018-01-11 01:13
@moriamiller since the age ranges for the program are `5 -13` they do do not fall outside the range of 6 -12 and inside the range of 2 -19. So you need to select `2-5 Tot` + `6 -12 Youth` + `Teen 13 -19`, this filters on the lowest age 2 to the highest rage 19

**Comment by andrewviren** [comment] 2018-01-11 16:19
@bdolly can we have the age range filtering do the opposite (i.e. be inclusive rather than exclusive)? This fits better with how someone might seek for programs for their youth.

**Comment by andrewviren** [comment] 2018-01-24 17:04
This issue seems to have persisted:

Reproduce:

1. Click "Athletic"
2. Add filter: Female: get three results
2. Add filter: teen: get two results (the one with age range 12-21 is **excluded**. We would want this to be included since it overlaps with the filtered age group.

@moriamiller can you reopen?

**Comment by karissademi** [comment] 2018-01-30 20:39
Closed in #174

**Closed by karissademi** 2018-01-30 20:39 UTC
Labels: feature, priority - high
