### ISSUE TITLE
Clicking 

### ISSUE THREAD

**Issue by andrewviren** [CityOfPhiladelphia/parks-rec-finder#107] opened 2018-01-23 22:04 UTC
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  |#/activities|  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

After I search for a zipcode and change the map zoom or focus, I expect the map to refresh and recenter itself when I click on Finder link in upper left of page.

###Observed Behavior

If I search a zipcode (19143), zoom out and then click the finder link at the top, I am taken back to the home page, but the map does not refresh and keeps whatever view I was last on.

> Steps to Reproduce

1. Opened finder
2. Typed "19143" into zip code search and hit enter.
3. zoom or pan to any part of the map; choose any program or location to zoom into that location
4. Clicked Finder Link in upper left corner.

#### Proposed Solution
As a user, if I scrolled too far from my search results or zoomed too far in or out, I would want to be able to start over from a zoomed out map by clicking "Finder".

**Comment by timwis** [comment] 2018-01-23 22:15
Should be quick fix. `src/components/pprf-header.vue` L34

```html
        <router-link class="app-title" to="/">
            <h2 class="text-nopad">FINDER</h2>
        </router-link>
```
Just change it from `<router-link>` to `<a href"/">`

Sara's working on that file right now so don't want to create merge conflict.

**Comment by timwis** [comment] 2018-01-24 10:44
Assuming this is a duplicate of #109 so closing in favour of that since it has screenshots and more detail

**Closed by timwis** 2018-01-24 10:44 UTC
